# =========================
# Stage 1: Build
# =========================
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["QLHopDongHoSo.API/QLHopDongHoSo.API.csproj", "QLHopDongHoSo.API/"]

RUN dotnet restore "QLHopDongHoSo.API/QLHopDongHoSo.API.csproj"

COPY . .

WORKDIR "/src/QLHopDongHoSo.API"

RUN dotnet build "QLHopDongHoSo.API.csproj" -c Release -o /app/build

RUN dotnet publish "QLHopDongHoSo.API.csproj" -c Release -o /app/publish /p:UseAppHost=false


# =========================
# Stage 2: Runtime
# =========================
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080

ENTRYPOINT ["dotnet", "QLHopDongHoSo.API.dll"]